Repository OUCH-cs/Server, pull requests merged in 2025-05, with the labels that each got.

#55 [REFACT] 건강상태 api 수정 및 예외처리 추가
  src/main/java/com/onebridge/ouch/controller/healthStatus/HealthStatusController.java
  src/main/java/com/onebridge/ouch/converter/HealthStatusConverter.java
  src/main/java/com/onebridge/ouch/repository/healthStatus/HealthStatusRepository.java
  src/main/java/com/onebridge/ouch/security/service/SignUpService.java
  src/main/java/com/onebridge/ouch/service/healthStatus/HealthStatusService.java
Labels: ♻️ refactoring

#54 [REFACT] 자가진단표 api 예외처리 추가
  src/main/java/com/onebridge/ouch/apiPayload/code/error/CommonErrorCode.java
  src/main/java/com/onebridge/ouch/apiPayload/handler/ExceptionAdvice.java
Labels: ♻️ refactoring

#56 [FEAT] 마이페이지 api 구현 - profile 만
  src/main/java/com/onebridge/ouch/controller/mypage/MypageController.java
  src/main/java/com/onebridge/ouch/converter/MypageConverter.java
  src/main/java/com/onebridge/ouch/dto/mypage/request/MypageProfileUpdateRequest.java
  src/main/java/com/onebridge/ouch/dto/mypage/response/MypageGetProfileResponse.java
  src/main/java/com/onebridge/ouch/dto/user/request/MypageUserInfoUpdateRequest.java
  src/main/java/com/onebridge/ouch/service/mypage/MypageService.java
Labels: ✨ feature

#59 [FEAT] Ouch Guide, Visit Guide, 자가진단 알고리즘 API 구현 및 구조화 조회 기능 추가 (#58)
  src/main/java/com/onebridge/ouch/apiPayload/code/error/CommonErrorCode.java
  src/main/java/com/onebridge/ouch/controller/guide/MedicalVisitGuideController.java
  src/main/java/com/onebridge/ouch/controller/guide/OuchGuideController.java
  src/main/java/com/onebridge/ouch/controller/selfDiagnosis/DiagnosisAlgorithmController.java
  src/main/java/com/onebridge/ouch/controller/selfDiagnosis/SelfDiagnosisController.java
  src/main/java/com/onebridge/ouch/controller/symptom/SymptomController.java
  src/main/java/com/onebridge/ouch/converter/SelfDiagnosisConverter.java
  src/main/java/com/onebridge/ouch/domain/SelfDiagnosis.java
  src/main/java/com/onebridge/ouch/domain/User.java
  src/main/java/com/onebridge/ouch/dto/guide/MedicalVisitGuideStep.java
  src/main/java/com/onebridge/ouch/dto/guide/OuchGuideEntry.java
  src/main/java/com/onebridge/ouch/dto/selfDiagnosis/request/DiagnosisAlgorithmRequest.java
  src/main/java/com/onebridge/ouch/dto/selfDiagnosis/request/DiagnosisUpdateRequest.java
  src/main/java/com/onebridge/ouch/dto/selfDiagnosis/request/SelfDiagnosisRequest.java
  src/main/java/com/onebridge/ouch/dto/selfDiagnosis/response/DiagnosisAlgorithmMapping.java
  src/main/java/com/onebridge/ouch/dto/selfDiagnosis/response/GetDiagnosisByUserIdResponse.java
  src/main/java/com/onebridge/ouch/dto/selfDiagnosis/response/GetDiagnosisResponse.java
  src/main/java/com/onebridge/ouch/service/guide/MedicalVisitGuideService.java
  src/main/java/com/onebridge/ouch/service/guide/OuchGuideService.java
  src/main/java/com/onebridge/ouch/service/healthStatus/HealthStatusService.java
  src/main/java/com/onebridge/ouch/service/medicalRecord/MedicalRecordService.java
  src/main/java/com/onebridge/ouch/service/selfDiagnosis/DiagnosisAlgorithmService.java
  src/main/java/com/onebridge/ouch/service/selfDiagnosis/SelfDiagnosisService.java
  src/main/java/com/onebridge/ouch/service/user/UserService.java
  src/main/resources/data/diagnosis_algorithm.json
  src/main/resources/data/medical_visit_guide.json
  src/main/resources/data/ouch_guide.json
Labels: ✨ feature

#62 자가진단, 의료기록, 건강상태 수정 api 수정
  src/main/java/com/onebridge/ouch/converter/HealthStatusConverter.java
  src/main/java/com/onebridge/ouch/converter/MedicalRecordConverter.java
  src/main/java/com/onebridge/ouch/converter/SelfDiagnosisConverter.java
  src/main/java/com/onebridge/ouch/domain/HealthStatus.java
  src/main/java/com/onebridge/ouch/domain/SelfDiagnosis.java
  src/main/java/com/onebridge/ouch/domain/Summary.java
  src/main/java/com/onebridge/ouch/domain/mapping/MedicalRecord.java
  src/main/java/com/onebridge/ouch/service/healthStatus/HealthStatusService.java
  src/main/java/com/onebridge/ouch/service/medicalRecord/MedicalRecordService.java
  src/main/java/com/onebridge/ouch/service/selfDiagnosis/SelfDiagnosisService.java
Labels: ♻️ refactoring

#65 [FEAT] 병원 위치 기반 거리순 정렬 API, 병원 상세 정보 조회 API, 진료과 리스트 조회 API 구현
  .gitignore
  src/main/java/com/onebridge/ouch/controller/hospital/HospitalController.java
  src/main/java/com/onebridge/ouch/domain/Department.java
  src/main/java/com/onebridge/ouch/domain/Hospital.java
  src/main/java/com/onebridge/ouch/domain/mapping/HospitalDepartment.java
  src/main/java/com/onebridge/ouch/domain/tempDomain/Department.txt
  src/main/java/com/onebridge/ouch/dto/hospital/response/AllDepartmentResponse.java
  src/main/java/com/onebridge/ouch/dto/hospital/response/HospitalDetailResponse.java
  src/main/java/com/onebridge/ouch/dto/hospital/response/HospitalDistanceResponse.java
  src/main/java/com/onebridge/ouch/repository/hospital/HospitalDepartmentRepository.java
  src/main/java/com/onebridge/ouch/repository/hospital/HospitalRepository.java
  src/main/java/com/onebridge/ouch/service/department/DepartmentService.java
  src/main/java/com/onebridge/ouch/service/hospital/HospitalDetailService.java
  src/main/java/com/onebridge/ouch/service/hospital/HospitalSearchService.java
  src/main/resources/data/department.json
Labels: ✨ feature

#73 [CICD] 25.05.30 main 브랜치 배포
  src/main/java/com/onebridge/ouch/controller/selfDiagnosis/DiagnosisAlgorithmController.java
  src/main/java/com/onebridge/ouch/dto/guide/MedicalVisitGuideStep.java
  src/main/java/com/onebridge/ouch/dto/guide/OuchGuideEntry.java
  src/main/java/com/onebridge/ouch/dto/hospital/response/AllDepartmentResponse.java
  src/main/java/com/onebridge/ouch/dto/selfDiagnosis/response/DiagnosisAlgorithmMapping.java
  src/main/java/com/onebridge/ouch/realtime/RealtimeSessionController.java
  src/main/java/com/onebridge/ouch/service/guide/OuchGuideService.java
  src/main/java/com/onebridge/ouch/service/selfDiagnosis/DiagnosisAlgorithmService.java
  src/main/resources/data/department.json
  src/main/resources/data/diagnosis_algorithm.json
  src/main/resources/data/diagnosis_algorithm_V1.json
  src/main/resources/data/medical_visit_guide.json
  src/main/resources/data/medical_visit_guide_V1.json
  src/main/resources/data/ouch_guide.json
  src/main/resources/data/ouch_guide_V1.json
Labels: 🖧 cicd
