Repository OUCH-cs/Server, pull requests merged in 2025-04, with the labels that each got.

#38 [FIX] 인증 로직 개선 및 JWT 직렬화 방식 수정
  src/main/java/com/onebridge/ouch/security/provider/OuchUserAuthenticationProvider.java
  src/main/java/com/onebridge/ouch/security/tokenManger/JwtTokenManager.java
Labels: 🔨 fix

#40 [REFACT] 도메인 연관관계 개선 및 엔티티 구조 리팩토링 (복합키 제거, 연관명칭 통일, 생명주기 관리 명확화) (#39)
  src/main/java/com/onebridge/ouch/converter/MedicalHistoryConverter.java
  src/main/java/com/onebridge/ouch/domain/HealthStatus.java
  src/main/java/com/onebridge/ouch/domain/Hospital.java
  src/main/java/com/onebridge/ouch/domain/Language.java
  src/main/java/com/onebridge/ouch/domain/Nation.java
  src/main/java/com/onebridge/ouch/domain/SelfDiagnosis.java
  src/main/java/com/onebridge/ouch/domain/Summary.java
  src/main/java/com/onebridge/ouch/domain/Translation.java
  src/main/java/com/onebridge/ouch/domain/User.java
  src/main/java/com/onebridge/ouch/domain/mapping/DiagnosisSymptom.java
  src/main/java/com/onebridge/ouch/domain/mapping/HospitalDepartment.java
  src/main/java/com/onebridge/ouch/domain/mapping/MedicalRecord.java
  src/main/java/com/onebridge/ouch/domain/mapping/compositeKey/DiagnosisSymptomPK.java
  src/main/java/com/onebridge/ouch/domain/mapping/compositeKey/HospitalCategoryPk.java
  src/main/java/com/onebridge/ouch/domain/tempDomain/PrivateInformation.txt
  src/main/java/com/onebridge/ouch/repository/medicalHistory/MedicalHistoryRepository.java
  src/main/java/com/onebridge/ouch/service/LanguageService.java
  src/main/java/com/onebridge/ouch/service/medicalHistory/MedicalHistoryService.java
  src/main/java/com/onebridge/ouch/web/controller/LanguageController.java
Labels: ♻️ refactoring

#33 [FEAT] 의료기록 CRUD api 구현
  src/main/java/com/onebridge/ouch/apiPayload/code/error/MedicalRecordErrorCode.java
  src/main/java/com/onebridge/ouch/controller/medicalRecord/MedicalRecordController.java
  src/main/java/com/onebridge/ouch/converter/MedicalRecordConverter.java
  src/main/java/com/onebridge/ouch/domain/Summary.java
  src/main/java/com/onebridge/ouch/domain/mapping/MedicalRecord.java
  src/main/java/com/onebridge/ouch/dto/medicalRecord/request/MedicalRecordCreateRequest.java
  src/main/java/com/onebridge/ouch/dto/medicalRecord/request/MedicalRecordUpdateRequest.java
  src/main/java/com/onebridge/ouch/dto/medicalRecord/response/DateAndHospital.java
  src/main/java/com/onebridge/ouch/dto/medicalRecord/response/GetMedicalRecordResponse.java
  src/main/java/com/onebridge/ouch/repository/medicalRecord/MedicalRecordRepository.java
  src/main/java/com/onebridge/ouch/repository/summary/SummaryRepository.java
  src/main/java/com/onebridge/ouch/service/medicalRecord/MedicalRecordService.java
Labels: ✨ feature

#37 [FEAT] 자가진단표 api 구현
  src/main/java/com/onebridge/ouch/apiPayload/code/error/DiagnosisErrorCode.java
  src/main/java/com/onebridge/ouch/controller/selfDiagnosis/SelfDiagnosisController.java
  src/main/java/com/onebridge/ouch/controller/symptom/SymptomController.java
  src/main/java/com/onebridge/ouch/controller/user/UserController.java
  src/main/java/com/onebridge/ouch/converter/SelfDiagnosisConverter.java
  src/main/java/com/onebridge/ouch/converter/SymptomConverter.java
  src/main/java/com/onebridge/ouch/converter/UserConverter.java
  src/main/java/com/onebridge/ouch/domain/SelfDiagnosis.java
  src/main/java/com/onebridge/ouch/domain/common/BaseEntity.java
  src/main/java/com/onebridge/ouch/domain/enums/SymptomDuration.java
  src/main/java/com/onebridge/ouch/domain/enums/VisitType.java
  src/main/java/com/onebridge/ouch/dto/selfDiagnosis/request/AddSymptomsToDiagnosisRequest.java
  src/main/java/com/onebridge/ouch/dto/selfDiagnosis/request/DiagnosisCreateRequest.java
  src/main/java/com/onebridge/ouch/dto/selfDiagnosis/request/DiagnosisUpdateRequest.java
  src/main/java/com/onebridge/ouch/dto/selfDiagnosis/response/DiagnosisUpdateResponse.java
  src/main/java/com/onebridge/ouch/dto/selfDiagnosis/response/GetDiagnosisByUserIdResponse.java
  src/main/java/com/onebridge/ouch/dto/selfDiagnosis/response/GetDiagnosisResponse.java
  src/main/java/com/onebridge/ouch/dto/selfDiagnosis/response/GetSymptomsOfDiagnosisResponse.java
  src/main/java/com/onebridge/ouch/dto/symptom/response/GetSymptomResponse.java
  src/main/java/com/onebridge/ouch/dto/user/request/UserUpdateRequest.java
  src/main/java/com/onebridge/ouch/dto/user/response/AllUsersResponse.java
  src/main/java/com/onebridge/ouch/dto/user/response/MypageUserInfoResponse.java
  src/main/java/com/onebridge/ouch/dto/user/response/UserSignupResponse.java
  src/main/java/com/onebridge/ouch/repository/Symptom/SymptomRepository.java
  src/main/java/com/onebridge/ouch/repository/selfDiagnosis/SelfDiagnosisRepository.java
  src/main/java/com/onebridge/ouch/service/selfDiagnosis/SelfDiagnosisService.java
  src/main/java/com/onebridge/ouch/service/symptom/SymptomService.java
  src/main/java/com/onebridge/ouch/service/user/UserService.java
Labels: ✨ feature
